"""add_commit_groups

Revision ID: 3c1d45e4ad48
Revises: f3c5e2a1b4d7
Create Date: 2026-05-25 11:29:08.068720
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '3c1d45e4ad48'
down_revision = 'f3c5e2a1b4d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commit_groups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=True),
    sa.Column('github_sha', sa.String(), nullable=False),
    sa.Column('github_ref', sa.String(), nullable=False),
    sa.Column('commit_message', sa.String(), nullable=True),
    sa.Column('commit_author_name', sa.String(), nullable=True),
    sa.Column('commit_author_login', sa.String(), nullable=True),
    sa.Column('file_paths', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), server_default='pending_confirmation', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending_confirmation', 'processing', 'done', 'cancelled')", name='commit_groups_status_check'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_commit_groups_project_id', 'commit_groups', ['project_id'], unique=False)
    op.create_index('idx_commit_groups_status', 'commit_groups', ['status'], unique=False)
    op.create_index('idx_commit_groups_user_id', 'commit_groups', ['user_id'], unique=False)
    op.drop_index(op.f('idx_invite_tokens_token'), table_name='invite_tokens')
    op.add_column('projects', sa.Column('webhook_file_limit', sa.Integer(), server_default=sa.text('50'), nullable=False))
    op.add_column('projects', sa.Column('pipeline_paused', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.drop_index(op.f('idx_projects_team_id'), table_name='projects')
    op.add_column('tasks', sa.Column('commit_group_id', sa.Uuid(), nullable=True))
    op.alter_column('tasks', 'conflict_base',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tasks', 'conflict_ours',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tasks', 'conflict_theirs',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_tasks_team_id'), table_name='tasks')
    op.create_foreign_key(None, 'tasks', 'commit_groups', ['commit_group_id'], ['id'], ondelete='SET NULL')
    # Update tasks_status_check to include 'cancelled'
    op.drop_constraint('tasks_status_check', 'tasks', type_='check')
    op.create_check_constraint(
        'tasks_status_check',
        'tasks',
        "status IN ('queued', 'running', 'done', 'failed', 'published', 'conflict', 'cancelled')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tasks_status_check', 'tasks', type_='check')
    op.create_check_constraint(
        'tasks_status_check',
        'tasks',
        "status IN ('queued', 'running', 'done', 'failed', 'published', 'conflict')",
    )
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_index(op.f('idx_tasks_team_id'), 'tasks', ['team_id'], unique=False)
    op.alter_column('tasks', 'conflict_theirs',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tasks', 'conflict_ours',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tasks', 'conflict_base',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('tasks', 'commit_group_id')
    op.create_index(op.f('idx_projects_team_id'), 'projects', ['team_id'], unique=False)
    op.drop_column('projects', 'pipeline_paused')
    op.drop_column('projects', 'webhook_file_limit')
    op.create_index(op.f('idx_invite_tokens_token'), 'invite_tokens', ['token'], unique=True)
    op.drop_index('idx_commit_groups_user_id', table_name='commit_groups')
    op.drop_index('idx_commit_groups_status', table_name='commit_groups')
    op.drop_index('idx_commit_groups_project_id', table_name='commit_groups')
    op.drop_table('commit_groups')
    # ### end Alembic commands ###
