"""initial_schema

Revision ID: 9a7fd32c779a
Revises: 
Create Date: 2026-05-06 09:37:18.660607
"""

# ruff: noqa: E501, I001

from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '9a7fd32c779a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('github_id', sa.BigInteger(), nullable=True),
    sa.Column('github_login', sa.String(), nullable=True),
    sa.Column('github_access_token', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_users_github_id', 'users', ['github_id'], unique=True, postgresql_where=sa.text('github_id IS NOT NULL'))
    op.create_table('dictionary_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dict_type', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dict_entries_type', 'dictionary_entries', ['dict_type'], unique=False)
    op.create_index('idx_dict_entries_type_key', 'dictionary_entries', ['dict_type', 'key'], unique=True)
    op.create_table('notification_channels',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('webhook_url', sa.String(), nullable=True),
    sa.Column('bitrix_token', sa.String(), nullable=True),
    sa.Column('destination_type', sa.String(), nullable=True),
    sa.Column('destination_id', sa.String(), nullable=True),
    sa.Column('events', sa.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notification_channels_active', 'notification_channels', ['is_active'], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source_repo', sa.String(), nullable=False),
    sa.Column('source_branch', sa.String(), server_default='main', nullable=False),
    sa.Column('target_repo', sa.String(), nullable=False),
    sa.Column('target_branch', sa.String(), server_default='main', nullable=False),
    sa.Column('webhook_secret', sa.String(), nullable=False),
    sa.Column('exclude_patterns', sa.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_projects_user_id', 'projects', ['user_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('github_ref', sa.String(), nullable=False),
    sa.Column('github_sha', sa.String(), nullable=True),
    sa.Column('commit_message', sa.String(), nullable=True),
    sa.Column('source_file_sha', sa.String(), nullable=True),
    sa.Column('target_file_sha', sa.String(), nullable=True),
    sa.Column('original_content', sa.String(), nullable=False),
    sa.Column('translated_content', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default='queued', nullable=False),
    sa.Column('log', sa.String(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('queued', 'running', 'done', 'failed', 'published')", name='tasks_status_check'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tasks_created_at', 'tasks', ['created_at'], unique=False)
    op.create_index('idx_tasks_project_id', 'tasks', ['project_id'], unique=False)
    op.create_index('idx_tasks_repo_path', 'tasks', ['project_id', 'file_path'], unique=False)
    op.create_index('idx_tasks_status', 'tasks', ['status'], unique=False)
    op.create_table('publications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('published_by', sa.Uuid(), nullable=False),
    sa.Column('target_repo', sa.String(), nullable=False),
    sa.Column('target_path', sa.String(), nullable=False),
    sa.Column('commit_sha', sa.String(), nullable=False),
    sa.Column('target_file_sha_before', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['published_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_publications_published_by', 'publications', ['published_by'], unique=False)
    op.create_index('idx_publications_task_id', 'publications', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_publications_task_id', table_name='publications')
    op.drop_index('idx_publications_published_by', table_name='publications')
    op.drop_table('publications')
    op.drop_index('idx_tasks_status', table_name='tasks')
    op.drop_index('idx_tasks_repo_path', table_name='tasks')
    op.drop_index('idx_tasks_project_id', table_name='tasks')
    op.drop_index('idx_tasks_created_at', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('idx_projects_user_id', table_name='projects')
    op.drop_table('projects')
    op.drop_index('idx_notification_channels_active', table_name='notification_channels', postgresql_where=sa.text('is_active = true'))
    op.drop_table('notification_channels')
    op.drop_index('idx_dict_entries_type_key', table_name='dictionary_entries')
    op.drop_index('idx_dict_entries_type', table_name='dictionary_entries')
    op.drop_table('dictionary_entries')
    op.drop_index('idx_users_github_id', table_name='users', postgresql_where=sa.text('github_id IS NOT NULL'))
    op.drop_table('users')
    # ### end Alembic commands ###
